"""Initial migration

Revision ID: 64a4e5d9b03e
Revises: 
Create Date: 2025-08-06 12:51:45.413649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a4e5d9b03e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('makes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_makes_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('year >= 1900 AND year <= 2030', name='check_year_range'),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', 'make_id', name='uq_model_year_make')
    )
    with op.batch_alter_table('car_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_models_make_id'), ['make_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_models_year'), ['year'], unique=False)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_car_model_id'), ['car_model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_car_model_id'))

    op.drop_table('cars')
    with op.batch_alter_table('car_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_models_year'))
        batch_op.drop_index(batch_op.f('ix_car_models_name'))
        batch_op.drop_index(batch_op.f('ix_car_models_make_id'))

    op.drop_table('car_models')
    op.drop_table('users')
    with op.batch_alter_table('makes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_makes_name'))

    op.drop_table('makes')
    # ### end Alembic commands ###
