"""add vin unique constraint

Revision ID: 6904aeb87710
Revises: 5e927eb9d492
Create Date: 2025-08-28 07:19:22.350775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6904aeb87710'
down_revision: Union[str, Sequence[str], None] = '5e927eb9d492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_models', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('uq_model_year_make', table_name='car_models')
    op.drop_column('car_models', 'created_at')
    op.alter_column('cars', 'vin',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('makes', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('makes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makes', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.alter_column('makes', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('cars', 'vin',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('car_models', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.create_index('uq_model_year_make', 'car_models', ['name', 'year', 'make_id'], unique=True)
    op.alter_column('car_models', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
